[workspace]
members = [
    "src/keret-controller",
    "src/keret-adapter",
    "src/keret-controller-transmit",
    "src/keret-service-transmit",
    "src/keret-service",
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = true
